### ISSUE TITLE
Logo de la municipalidad de Córdoba

### ISSUE THREAD

**Issue by avdata99** [avdata99/feria-del-libro#15]
Me dijeron que el logo de la muni debe estar en la app.
Aplicalo por favor Gaston con instrucciones que indique Silvana.

**Comment by silvanaroche** [comment]
Andrés se encuentran en el splash y en el about us. Los logo de la Muni. 
avisen si hay que ponerlo en otro sitio…

**Comment by silvanaroche** [comment]
Gas, hola! fíjate si lo podes embeber en la imagen, si no te paso el bloque completo.
te adjunto el logo, y la imagen de como quedaría. 
Recordó que el logo no será visible vía email, porque todo es “Blanco”
avisame
Sil

 <<<< está acá
