### ISSUE TITLE
Achicar header home

### ISSUE THREAD

**Issue by avdata99** [avdata99/feria-del-libro#17]
Hacer menos alto el header de la home.
![image](https://cloud.githubusercontent.com/assets/3237309/18297845/4bc1f192-748a-11e6-807b-62595bffae24.png)

Dentro de las secciones o filtros si es necesario titular con los agrupadores pero en la home, no.

En la pantalla inicial el texto _Próximos eventos_ y _Elegí tu evento_ no parecen necesarios.
Allí debe estar el logo o el encabezado que se redefina en #1

**Comment by silvanaroche** [comment]
Ok tenemos que Re diseñar la app, y las templates de la app... 
pero eso es para comenzar recién mañana. 
saludos

**Comment by avdata99** [comment]
Primero lo que pase por slack y despues esto, de la forma mas simple que se pueda.

**Comment by silvanaroche** [comment]
![img-books-blanco](https://cloud.githubusercontent.com/assets/7537034/18324781/9c628dde-7514-11e6-8bb3-55afde3611fb.png)

**Comment by avdata99** [comment]
Dale gas @gastonframirez, esta bueno
