### ISSUE TITLE
Compartir en redes sociales

### ISSUE THREAD

**Issue by avdata99** [avdata99/feria-del-libro#19]
Permitir compartir en redes sociales la URL que se esté viistando.

Validar que sea compatible con web/apk

**Comment by gastonframirez** [comment]
@avdata99 faltaría instalar el plugin y trasladar los archivos que cambie a gh-pages. Ya habia empezado a trabajar en esta branch.

**Comment by gastonframirez** [comment]
@avdata99 Ya instalé el plugin y hice el merge con gh-pages. Funciona todo OK (en desktop comparte en Twitter y Facebook), en mobile si entras a la pagina te deja compartir en Facebook, Twitter y Whatsapp (y cuando compiles la app y la subas al market.. si queres por las dudas generá el apk y probalo en tu celu, debería dejarte compartir con todas las opciones que tenga el compartir de Android).
