### ISSUE TITLE
Definir imagen para compartir en facebook

### ISSUE THREAD

**Issue by avdata99** [avdata99/feria-del-libro#24]
Si se comparte algun evento en facebook no muestra imagen
![seleccion_382](https://cloud.githubusercontent.com/assets/3237309/18496728/a4dc9ce0-79fe-11e6-9eca-ffc7aad69090.png)

Definir los _metas_ requeridos para que Facebook interprete bien lo que se va a compartir

```
        <meta property='og:locale' content='es_ES'/>
    <meta property='og:type' content='website'/>
    <meta property='og:title' content='Titulo del Sitio web'/>
    <meta property='og:description' content='Descripcion del sitio web, articulo, pagina'/>
    <meta property='og:url' content='URL del sitio web'/>
    <meta property='og:site_name' content='Nombre del sitio web'/>
    <meta property="og:image" content="Imagen_del_articulo_pagina.jpg">
```

Usar los que tengan sentido, en el caso de la imagen elegir la mejor opción disponible, el logo de la feríá del libro es una opción válida sino hubiera otra mejor

**Comment by gastonframirez** [comment]
@silvanaroche necesito que me pases el logo de la feria en tamaño mayor a 200x200 (ahora creo que es 100x100.
Gracias!

**Comment by silvanaroche** [comment]
![200x200px-logo-feria-del-libro](https://cloud.githubusercontent.com/assets/7537034/18562478/36c8dafe-7b5a-11e6-9807-6bca83249267.png)

@gastonframirez adjunto el logo, cualquier cosita avisame.
saludos
