### ISSUE TITLE
Icono y splash de la app

### ISSUE THREAD

**Issue by avdata99** [avdata99/feria-del-libro#5]
Crear un ícono de la app. 64x64
Además una imagen splash para el inicio. Vamos a necesitar la misma en varios tamaños.
Con una de 480x800px por ahora andamos. 

Ponerlas en un directorio assets de este repo

**Comment by silvanaroche** [comment]
512 x 512 .png icon de la app. 
![512x512-icon-app-feria-del-libro](https://cloud.githubusercontent.com/assets/7537034/18286622/052e4df6-744a-11e6-8cd3-20823f31692a.png)
